from kmp_algorithm import KMP
from kmp_algorithm_cy import KMP as KMP_cy
import string
import random
import time

"""
text = 'ABCABAABCABAC'
pattern = 'CAB'

KMP(text, pattern)
"""

iteraciones = 30

"""
* Los textos se generarán aletoriamente de forma automática con las siguientes longitudes:
    * 500 caracteres
    * 1000 caracteres
    * 2000 caracteres
* Los patrones de búsqueda serán de 5 caracteres cada uno y serán aleatorios
"""

texts = [''.join(random.choice(string.ascii_uppercase) for i in range(500)), ''.join(random.choice(string.ascii_uppercase) for i in range(1000)), ''.join(random.choice(string.ascii_uppercase) for i in range(2000))]

patterns = [''.join(random.choice(string.ascii_uppercase) for i in range(5)) for j in range(3)]

print_format = "{:.5f},{:.5f}\n"

"""
Cargas generadas
Patrón -> RNRFBNAUTNYWSCANJKEEFXDUZXJLHHUTYNXRQGRARTWGAZTHNBPZNQSPQNKSUAPBFQWVGTZNUOWDOTIQFRCRYMHDGMWTBOXLRIBFAMWMCEFNSNXXKWNPDNHHGZWJTPLWMNREGYROZHOQKYRSPXNCSHZIIQNOZBWBFLUBKBLNNAEOUJYMNIXAWCYYIXGCDWNYIXIQQSDHTRDTARBYYPLBTWWRANKYVWKIJRVPVNIQRKNKAOMAVOSKEDFRFRJKOUVICMRNVBITRICJRFYIAPPZYSXETCTHMNIQQDIQTFIVITEOIAVEFXZACXTULYOTJZHQVIRCKDLKWHNHBCTTENOPHNQJDHBVKHDSEYWHUGYEJVIJNKENTDHLONTEQIZQREAQROFKECJJNUMYQXYDUSINXDWYLVMDNBWOKKJJBYNHEQOIUANKZWDETIBXJIZMUJACBISLKSMKKXAXVWAYTMEIESLTZYGECPYUKTVPVXHWHUDBCDODFITN
Carga ->HLJDS
Patrón -> QOBBHUSIRDFQXZHPZXDUFBPGFXYFZJJCJZLREBMSCOJZVOEFABIVUJDKPAGBPLOYOOPBAOLTHKQQQCLZIOBVOWSMQTKYBIZFHAYHTVBTREQXVJBMVNJYBJOGQCAZKZUPPQFFDTBWGFAWPBJRDRHLXQOESLKAWJTGCOICKQCZZUEDTMWBCQMOPGWTGZMOXNPUWNYAENLUKOYFHGFEMNILRKKEEFRPJIADRQGEWHMNNKGBJTDNMUOJUMVMWELQNABOBDNIPDBMFPBXQREZFCEPINWICPUZUHRQDKTDFSOYNLHFKPAROILOWESQEQDLXTUCXNGERJGMHXNZGHBQGRCMYPSKOLCZUJABDTNTYDKCZBXWNVZNTVAXWONVDKDEQAJYCFMNYTGKIEGKMZDYODFAZJYOFHRMCFRAYSPMCWXCBFLBACQGWLLTVMFULROGMMLBQYSAOKKTTNEIOYHXMUQTEBJSLEKKPFFXDINPSXCFWFKROKBTHCZDWIYCPVVVHAHMWAPEINZQVGYMZNXHZCOTTVGLORHIGFKBVSBUJVMNFFYJJVVRSHLTBCOLLMFYNPFJXSJIGSBFNVVZCGVBEUCAQUTOODWHMIZAPHWFVMSCXEJPXGKLHOFKTSTWSTTCUKSXRMXVKQPJIBHEYLISBJIUHLBDGYSGLQMECWNKMTNUHRFGYHZSIYWPYLBKWFSZQYZNQUGQTFGKORYEWTXVWAGWAWONDYYNYUJDGOQPNAJTMVWSPBXWCJOQMUTQDLKDEWITISFXQJCWOMNBHPNUSVIFKDTDWCGXVSEOBIKQZDTZCZOFKBPKDOWPSKKRLTIIDRMSOIOSGBTTGBTRLQMHIMTCGVPGZDQOLKFBKABUMLBQCDIFDQGNXPSHTMPGRWBWQCUCSBWCIPUSUNAXBVDPPSCKVSIIFFNKWALYVYOJTDUBEQXTHBTGUGNFKWEDKBTAUGZMUIJNDNLZLPUHGMQFKYAJOQCHOFXNQPHOSFVTHDDH
Carga ->PPHQT
Patrón -> KLBEYZKRAAGTMXLNWKYFKKRFTBHRWDDXYPGGWDUDWAGKXAUEBGQYXSTQNOXICERUZEZISHAQBILHBURBLZXGMVQIHBYPZGTWKVUMFEXCFBVSXOLERQCLQTOXXDXPPREYNBMKSGPLAJFEEIBAGDUTLZPUPEGPTGWHDFIRZARTQMLRAHOEUKXJKXMFKLAAAFNVZGHNGAOXPHDOFJOEDXQAWIWCAQLLFJWWLFUVCLUQHNFKKDLWXFQUNNXBGRSPHATWCSZEGTUYWXIBGNYUPWKSLZFPSQRGZEZLIGUFGQAHDRMOPBYQIQBNPESZZKMMDQOUFUCSSGUCWGQXYLLZKCSDJJTKIZMFIKRDIZVKLUKXWUKITWVMIJRDMIDIRFIJLWJMSZZUSQIBRRTJJLAVVAITJBNJWDMSSJFVLCZJBEAUVRNURBJBOGLUVYQYTIRRGOIOKIJVFGPIXQJZOMJYUANVMLGFWTASSSMQSVSFFUWPBCIPBXFPLGOOVPEXCCUAMWSPOSVAZBIXXUVCSAKJSVMJUPEKOARCGXXTSVPEKZYFBINPLEJEHZKUWLYSESSVMQJTAHFHCNVGOSZKLTGVVTJPLYPRBAPPIIXEPYQCGQVRFTZMJJKJAQGNPNJLYHAGOXJVLLZHFPIZEVESUTBWBLIYDSJXSQFBOPDGKMKOEOSCSEOHYUAYDTGURXLHSNSFVKMLXUYUGGPGZOWGELOQVTNLKQYDRCPUVJEQAEOZYGNKZAGXEJYMXCKCMTADECJKLFGPNELQSZGRJQEQNYXXPXLGYIGVVPZODOUKSLQRNJSSYJPQZSJANPTLQBXOKJQRMOPHTMXQFOUGQCIGEGYPJGKKVFUXZFKTXGOXIOIUSQVKPAWPFIHWIOYAYXGBNZXVZQERUQCELGHJDHMIMBSCPZXOIQVKTLGMERIFIQTQIONIARNORTFIAYHPRETFOMRDKLRKCNMFTNPKSKYPSXVDEIRMSSDXYYNFAHCIPAFWBZYVWCKXJMHIZEEJZIEAYITSUKNOOTXVCDVLBPHOCRYUQZNKYXSUQKHEURDPYBYSVUMSCEMQRVCKBVKARTDPITTKQJNKDCYOVKHETBETQXKNESWVGMVHWCLQTUZLWVEGDHPFFSZBCWQFYZTIDACYQWGQPTDYUHPJIKMCVSLDLCHXTVVJBZUJHAKROBWCEUZZWKPJYYJVEAADHMHNLMXQLZAMZPYWNHODGKGKVIGQIYPLTNSNSSUWIENFKEZLHHNNPXGCENZPCCWOVDGJEKSRTWOCQLHYUOTYDXJTNXOUOUMSPCMNMQPJYPXGNZVDRUULMLKSSGXLBFOKTBJZBCTSERSNYBHAFNZWWEUZYHCVKPFVCDFMOJBQOJHVXBPBYVDQLOAMWWCYONZRCSTYIMFDZWWMYXBKYAYODIZBEFDHCPSMRZEQJPTSKMWRFGNCYTVVYXENGBAQFWNMSQYPELRKWZOSIZQGUYVQMRZSKKHNNCEFNZEPCNRBUJEYUYYZYHZYUGYEVXDWMMIEEUKMLAQKBCKKAWOHINBVSLVXCRYRZUJPMFUYJSAZRGZMFRBVFMKREUVOPSZYLRGEPBPPTZEDTFOHCNPHHPXXIXCBYSTSYHHAIJWVSHGHDMSNUKODTILYNAAEVRWUZDXUNURKCRNGJWOYEYVGGKBQAMABNNLYYHBMBGUDKJAMGRKKXJKZRHRBGGBYYGPYMJXSDOIRORTHGKJPFGOYMATKWESOSEEGYLUYQLPJVQOGVKCZDITHTWSWRTLMAYABWAISDBVYXKIUFNBFPXSJRALILRVDJGJOCLRAJSOLBOGEEXHUYHQVUUGVSYZBVJEFNQHIYUBMKUSSKIJIJNCOAEFXHJWZEQQVEXQCLSUHTCOVBKSZLYFBONMAYIMPCESIBQMKKTGGIERVCZWHJIZIFVTVOIDVEIHOZCBIDGTCFSBXNCEIPMSNWIIJRTCTTWKBPLCGVITXFCVUKVLQAMIRKWLWSXRPPARNRKRW
Carga ->QGMZJ
"""

#print("Cargas generadas")
for i in range (len(texts)):

    #Clears csv
    f = open(f"kmp{i}.csv","w")
    f.truncate()
    f.close()

    text = texts[i]
    pattern = patterns[i]
    #print("Patrón -> {}\nCarga ->{}".format(text,pattern))

    with open(f"kmp{i}.csv","a") as archivo:
        archivo.write("python, cython\n")

    for j in range(iteraciones):
        init_time=time.time()
        KMP(text,pattern)
        end_time=time.time()

        time_python = end_time - init_time

        init_time=time.time()
        KMP_cy(text,pattern)
        end_time=time.time()

        time_cython = end_time - init_time

        with open(f"kmp{i}.csv","a") as archivo:
            archivo.write(print_format.format(time_python,time_cython))

